pipeline:
  name: STO-Master
  identifier: STOMaster
  projectIdentifier: tanays
  orgIdentifier: traceablecsindia
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tanaysgithub
        repoName: webgoat
        build: <+input>
  stages:
    - stage:
        name: Build SCA  SAST
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            override: true
            paths: []
          buildIntelligence:
            enabled: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerHubReadOnly
                    image: maven:3.9.9-amazoncorretto-23-debian
                    shell: Sh
                    command: mvn clean package -Dmaven.test.skip=true
              - stepGroup:
                  name: SAST
                  identifier: SAST
                  steps:
                    - parallel:
                        - step:
                            type: Semgrep
                            name: Semgrep_1
                            identifier: Semgrep_1
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: info
                              resources:
                                limits:
                                  memory: 3Gi
                                  cpu: 3000m
                        - step:
                            type: Bandit
                            name: Bandit_1
                            identifier: Bandit_1
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: info
              - stepGroup:
                  name: SecretDetection
                  identifier: SecretDetection
                  steps:
                    - step:
                        type: Gitleaks
                        name: Gitleaks_1
                        identifier: Gitleaks_1
                        spec:
                          mode: orchestration
                          config: default
                          target:
                            type: repository
                            detection: auto
                          advanced:
                            log:
                              level: info
              - step:
                  type: Checkov
                  name: Checkov_1
                  identifier: Checkov_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        when:
          pipelineStatus: Success
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: Ignore
    - stage:
        name: DockerImage
        identifier: DockerImage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: Build
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: dockerHubReadOnly
                    repo: tanayharness/tanaysethi-traceable
                    tags:
                      - latest
                    envVariables:
                      PLUGIN_TAR_PATH: /harness/webgoat.tar
                      PLUGIN_NO_PUSH: "true"
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerHubReadOnly
                    image: alpine
                    shell: Sh
                    command: ls -larth
              - parallel:
                  - step:
                      type: Checkov
                      name: Checkov
                      identifier: Checkov
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: repository
                          detection: auto
                        advanced:
                          log:
                            level: info
                  - step:
                      type: Grype
                      name: Grype_1
                      identifier: Grype_1
                      spec:
                        mode: orchestration
                        config: default
                        target:
                          type: container
                          detection: auto
                        advanced:
                          log:
                            level: info
                        privileged: true
                        image:
                          type: docker_v2
                          tag: latest
                          name: webgoat
                      failureStrategies:
                        - onFailure:
                            errors:
                              - AllErrors
                            action:
                              type: Ignore
    - stage:
        name: DAST
        identifier: DAST
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: Build
          execution:
            steps:
              - step:
                  type: Traceable
                  name: Traceable
                  identifier: Traceable
                  spec:
                    auth:
                      access_token: MTJmZDAxOTAtM2NmOC00NGMxLWE4YWItZjc3NDY3ZTA3MTk1
                      domain: https://api.apac.traceable.ai
                    mode: orchestration
                    config: default
                    target:
                      type: instance
                      detection: auto
                    advanced:
                      log:
                        level: info
                    tool:
                      suite_id: 2dbf201f-01c3-49ad-88d1-a214b793c976
                      runner_id: a5449d28-5cea-5d1d-ad95-e6873ab70b89
    - stage:
        name: SCS
        identifier: SCS
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: Build
          execution:
            steps:
              - step:
                  type: SscaOrchestration
                  name: SBOM Orchestration_1
                  identifier: SBOMOrchestration_1
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    source:
                      type: docker
                      spec:
                        connector: dockerHubReadOnly
                        image: tanayharness/tanaysethi-traceable:latest
                    attestation:
                      type: cosign
                      spec:
                        privateKey: SBOM_Attest
                        password: SBOM_Attest_02
                    sbom_drift:
                      base: last_generated_sbom
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
              - step:
                  type: SscaCompliance
                  name: SCS Compliance_1
                  identifier: SCSCompliance_1
                  spec:
                    source:
                      type: github
                      spec:
                        connectorRef: tanaysgithub
                        repoName: webgoat
                        scan_org: true
