pipeline:
  name: STO-Master
  identifier: STOMaster
  projectIdentifier: tanays
  orgIdentifier: traceablecsindia
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tanaysgithub
        repoName: WebGoat
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: "Build "
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerHubReadOnly
                    image: maven:3.9.9-amazoncorretto-23-debian
                    shell: Sh
                    command: mvn clean package -Dmaven.test.skip=true
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build
                  identifier: Build
                  spec:
                    connectorRef: dockerHubReadOnly
                    repo: tanayharness/webgoat
                    tags:
                      - latest
                    envVariables:
                      PLUGIN_TAR_PATH: /harness/webgoat.tar
                      PLUGIN_NO_PUSH: "true"
              - stepGroup:
                  name: Security Tests
                  identifier: Security_Tests
                  steps:
                    - parallel:
                        - step:
                            type: Owasp
                            name: Owasp_1
                            identifier: Owasp_1
                            spec:
                              target:
                                detection: auto
                                type: repository
                              advanced:
                                log:
                                  level: info
                                args: {}
                              mode: orchestration
                              config: default
                        - step:
                            type: OsvScanner
                            name: OsvScanner_1
                            identifier: OsvScanner_1
                            spec:
                              target:
                                detection: auto
                                type: repository
                              advanced:
                                log:
                                  level: info
                                args: {}
                              mode: orchestration
                              config: default
                        - step:
                            type: Semgrep
                            name: Semgrep_1
                            identifier: Semgrep_1
                            spec:
                              target:
                                detection: auto
                                type: repository
                              advanced:
                                log:
                                  level: info
                                args: {}
                              mode: orchestration
                              config: default
                        - step:
                            type: Gitleaks
                            name: Gitleaks_1
                            identifier: Gitleaks_1
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: info
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        when:
          pipelineStatus: Success
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: Ignore
    - stage:
        name: DAST
        identifier: DAST
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            useFromStage: Build
          execution:
            steps:
              - step:
                  type: Traceable
                  name: Traceable
                  identifier: Traceable
                  spec:
                    auth:
                      access_token: MTJmZDAxOTAtM2NmOC00NGMxLWE4YWItZjc3NDY3ZTA3MTk1
                      domain: https://api.apac.traceable.ai
                    mode: orchestration
                    config: default
                    target:
                      type: instance
                      detection: auto
                    advanced:
                      log:
                        level: info
                    tool:
                      suite_id: 2dbf201f-01c3-49ad-88d1-a214b793c976
                      runner_id: a5449d28-5cea-5d1d-ad95-e6873ab70b89
    - stage:
        name: SCS
        identifier: SCS
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: SscaOrchestration
                  name: SBOM Orchestration_1
                  identifier: SBOMOrchestration_1
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    source:
                      type: docker
                      spec:
                        connector: dockerHubReadOnly
                        image: tanayharness/webgoat
                    attestation:
                      type: cosign
                      spec:
                        privateKey: SBOM_Attest
                        password: SBOM_Attest_02
                    sbom_drift:
                      base: last_generated_sbom
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
              - step:
                  type: SscaCompliance
                  name: SCS Compliance_1
                  identifier: SCSCompliance_1
                  spec:
                    source:
                      type: github
                      spec:
                        connectorRef: tanaysgithub
                        repoName: webgoat
                        scan_org: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
